# This automatically builds reflow and adds to the releases tab

name: Autobuild

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/crazy-max/xgo:latest
    steps:
      - name: Build Reflow
        run: |
          xgo -targets "windows/*,darwin/*,linux/arm,linux/arm64,linux/386,linux/amd64" github.com/Zaprit/Reflow
          ls
          for i in $(ls)
          do
          zip $(basename $i .exe).zip $i
          done
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Reflow CI build"
          files: |
            Reflow-*
            - name: action-zip
