# This automatically builds reflow and adds to the releases tab

name: Autobuild

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crazymax/xgo:latest
    steps:
      - name: Get Dependencies
        run: |
          apk add --no-cache zip
      - name: Build Reflow
        run: |
          xgo github.com/Zaprit/Reflow
          for i in $(ls ./reflow-)
          do
          zip $(basename $i .exe).zip $i
          done
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Reflow CI build"
          files: |
            reflow-*.zip
            
